### ISSUE TITLE
Dökümanlar: HTML5 Web Workers Syntax Hatası

### ISSUE THREAD

**Issue by aykutkardas** [sercaneraslan/sercaneraslan.github.io#1]
Bağlantıdaki dökümanda javascript kodumuz bölümünde küçük bir syntax hatası var.
http://sercaneraslan.com/html5/web-workers

```js
document.getElementById('result').innerHTML = 'Tarayıcınız Web Workers'ı desteklemiyor!';
```

**Comment by sercaneraslan** [comment]
Teşekkürler Aykut, düzelttim 👍

**Comment by aykutkardas** [comment]
Ek olarak menü açılınca tekrar kapanmıyor. 
Bu güzel doküman için ayrıca teşekkür ederim. +1

**Comment by sercaneraslan** [comment]
Rica ederim, menülerin açılma durumlarını da düzelttim, teşekkür ederim 👍
